- name: Installing Prometheus
  hosts: prometheus
  become: true
  roles:
    - role: ansible-prometheus
      prometheus_config_scrape_configs:
        - job_name: 'prometheus'
          honor_labels: true
          scrape_interval: '15s'
          scrape_timeout: '3s'
          metrics_path: '/metrics'
          scheme: 'http'
          static_configs:
            - targets:
                - '<ippublica de prometheus>:9090' # Prometheus itself
                - '<ip de los nodos que sacara info>:9100' # Node exporter
        - job_name: 'consul-services' #probablemente limpiar esto
          consul_sd_configs:
            - server: "35.184.41.190:8500"
